spring:

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://mysqldb:3306/company_employee?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: fortest2021java@gmail.com
    password: fortest2021
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    template:
      path: /mail/verifyTemplate
